version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: ./Server
      dockerfile: ./Dockerfile

  client:
    image: client
    build:
      context: ./front
      dockerfile: ./Dockerfile
    depends_on:
      - server