version: '3.4'

services:
  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
      - "5098"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
      - ${APPDATA}/ASP.NET/Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro

  client:
    ports: 
      - "5000:3000"