version: '3.4'

services:
  server:
    image: lenabakova17/server
    build:
      context: ./Server
      dockerfile: ./Dockerfile

  client:
    image: lenabakova17/client
    build:
      context: ./front
      dockerfile: ./Dockerfile
    depends_on:
      - server