version: '3.4'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile

  client:
    image: client
    build:
      context: .
      dockerfile: front/Dockerfile
    depends_on:
      - server